version: '3.4'

services:
  catalogdb:
    image: mongo
    container_name: catalogdb
    restart: always
    volumes:
      - mongo_data:/data/db 
    ports:
      - "27017:27017"


  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.Api/Dockerfile
    container_name: catalog.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSetting:ConnectionString=mongodb://catalogdb:27017" 
    depends_on:
      - catalogdb
    ports:
      - "8000:80"

volumes:
  mongo_data: